[project]
name = "gaia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "gpxpy>=1.6.2",
    "requests>=2.32.4",
    "ruff>=0.12.4",
    "pre-commit>=4.0.1",
]
